//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purple.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PurpleEntities : DbContext
    {
        public PurpleEntities()
            : base("name=PurpleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblProperty> tblProperties { get; set; }
        public DbSet<tblStatusLookup> tblStatusLookups { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserType> tblUserTypes { get; set; }
        public DbSet<tblOffer> tblOffers { get; set; }
        public DbSet<tblToken> tblTokens { get; set; }
    }
}
