//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purple.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        public tblProperty()
        {
            this.tblOffers = new HashSet<tblOffer>();
        }
    
        public int PropertyID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool IsSold { get; set; }
    
        public virtual ICollection<tblOffer> tblOffers { get; set; }
    }
}
