USE [master]
GO

/****** Object:  Database [Purple]    Script Date: 22/04/2016 02:17:56 ******/
CREATE DATABASE [Purple]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Purple', FILENAME = N'F:\Databases\Purple.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Purple_log', FILENAME = N'E:\Logs\Purple_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Purple] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Purple].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Purple] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Purple] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Purple] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Purple] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Purple] SET ARITHABORT OFF 
GO

ALTER DATABASE [Purple] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Purple] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Purple] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Purple] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Purple] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Purple] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Purple] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Purple] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Purple] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Purple] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Purple] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Purple] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Purple] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Purple] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Purple] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Purple] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Purple] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Purple] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Purple] SET  MULTI_USER 
GO

ALTER DATABASE [Purple] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Purple] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Purple] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Purple] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Purple] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Purple] SET  READ_WRITE 
GO


